### ISSUE TITLE
支持下2017?

### ISSUE THREAD

**Issue by yingnierxiao** [zhaoqingqing/KSFramework_xlua#1]
能支持下2017?

**Comment by zhaoqingqing** [comment]
节日快乐，后续会支持。

**Comment by GuipengLiao** [comment]
现在好像不支持2017吧，gen生成warp代码直接报错

**Comment by zhaoqingqing** [comment]
支持的。你可以把xlua从plugins目录移出来。

**Comment by zhaoqingqing** [comment]
目前已支持unity2018，请切换到这个库：https://github.com/mr-kelly/KSFramework
