### ISSUE TITLE
Unity Version 2017.1.3f1 Generate Code报错

### ISSUE THREAD

**Issue by GuipengLiao** [zhaoqingqing/KSFramework_xlua#3]
抱歉穿不上图
首先是正确编译后正确输出
[SettingModuleEditor]Watching directory: Product/SettingSource
finished! use 2200 ms

然后是报错输出999条，截取部分如下：
1：Assets/XLua/Gen/Coroutine_RunnerWrap.cs(22,34): error CS0122: `XLua.ObjectTranslatorPool' is inaccessible due to its protection level

2：Assets/XLua/Gen/Coroutine_RunnerWrap.cs(22,64): error CS0029: Cannot implicitly convert type `XLua.ObjectTranslator [Assembly-CSharp-firstpass, Version=0.11.6783.20808, Culture=neutral, PublicKeyToken=null -- F:\ElieenLiao\CanKaoProject\KSFramework_xlua-master\Library\ScriptAssemblies\Assembly-CSharp-firstpass.dll]' to `XLua.ObjectTranslator [Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -- F:\ElieenLiao\CanKaoProject\KSFramework_xlua-master\Assets\XLua\Gen\WrapPusher.cs]'

3：Assets/XLua/Gen/Coroutine_RunnerWrap.cs(23,10): error CS0117: `XLua.Utils' does not contain a definition for `BeginObjectRegister'

4：Assets/XLua/Gen/Coroutine_RunnerWrap.cs(47,43): error CS0122: `XLua.ObjectTranslatorPool' is inaccessible due to its protection level

5：Assets/XLua/Gen/DelegatesGensBridge.cs(579,28): error CS1061: Type `XLua.ObjectTranslator' does not contain a definition for `Push' and no extension method `Push' of type `XLua.ObjectTranslator' could be found. Are you missing an assembly reference?

6：Assets/XLua/Gen/DelegatesGensBridge.cs(608,28): error CS1061: Type `XLua.ObjectTranslator' does not contain a definition for `Push' and no extension method `Push' of type `XLua.ObjectTranslator' could be found. Are you missing an assembly reference?

etcs

**Comment by GuipengLiao** [comment]
如果更换官网xlua最新版本库，会导致 
InvalidProgramException: wrong lib version expect:100 but got:104

然后更改代码配置文件
        const int LIB_VERSION_EXPECT = 104;

错误：
ArgumentException: An element with the same key already exists in the dictionary.
System.Collections.Generic.Dictionary`2[System.Type,XLua.OptimizeFlag].Add (System.Type key, OptimizeFlag value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404)
CSObjectWrapEditor.Generator.AddToList (System.Collections.Generic.List`1 list, System.Func`1 get, System.Object attr) (at Assets/Plugins/xLua/Src/Editor/Generator.cs:1264)
CSObjectWrapEditor.Generator.MergeCfg (System.Reflection.MemberInfo test, System.Type cfg_type, System.Func`1 get_cfg) (at Assets/Plugins/xLua/Src/Editor/Generator.cs:1289)
CSObjectWrapEditor.Generator.GetGenConfig (IEnumerable`1 check_types) (at Assets/Plugins/xLua/Src/Editor/Generator.cs:1394)
CSObjectWrapEditor.Generator.GenAll () (at Assets/Plugins/xLua/Src/Editor/Generator.cs:1532)


然后修改CSObjectWrapEditor.Generator.AddToList(List<Type> list, Func<object> get, object attr)
方法从
源代码：
                    foreach(var type in (obj as IEnumerable<Type>))
                    {
                            OptimizeCfg.Add(type, flag);
                    }
新代码：
                    foreach(var type in (obj as IEnumerable<Type>))
                    {
                        if (OptimizeCfg.ContainsKey(type))
                            OptimizeCfg[type] = flag;
                        else
                            OptimizeCfg.Add(type, flag);
                    }

然后回到之前没更换版本库的错误
finished! use 1780 ms
UnityEngine.Debug:Log(Object)
CSObjectWrapEditor.Generator:GenAll() (at Assets/Plugins/xLua/Src/Editor/Generator.cs:1546)

输出999条error

**Comment by GuipengLiao** [comment]
![snipaste_2018-07-28_14-04-58](https://user-images.githubusercontent.com/8604102/43353616-4a3518d6-926f-11e8-9abb-4283c972b7c0.png)

原因是一个在plugins程序集，一个在默认Unity程序集
但是如果把Xlua从Plugins文件夹移到Asset根目录下，又会产生KSFrameWork和KEgine无法引用Xlua命名空间的问题

**Comment by GuipengLiao** [comment]
已解决，请关闭，谢谢

**Comment by zhaoqingqing** [comment]
你可以把xlua从plugins目录移出来。
